package net.runelite.client.plugins.discordraredropnotifier;

import lombok.AllArgsConstructor;
import net.runelite.api.ItemID;

import java.util.Map;

@AllArgsConstructor
public enum NotifiyItems {
    // Slayer
    ABYSSAL_WHIP(ItemID.ABYSSAL_WHIP),
    GRANITE_MAUL(ItemID.GRANITE_MAUL),
    DRACONIC_VISAGE(ItemID.DRACONIC_VISAGE),
    WYVERN_VISAGE(ItemID.WYVERN_VISAGE),
    DRAGON_BOOTS(ItemID.DRAGON_BOOTS),
    IMBUED_HEART(ItemID.IMBUED_HEART),
    ETERNAL_GEM(ItemID.ETERNAL_GEM),
    DUST_BATTLESTAFF(ItemID.DUST_BATTLESTAFF),
    MIST_BATTLESTAFF(ItemID.MIST_BATTLESTAFF),
    BRINE_SABER(ItemID.BRINE_SABRE),
    LEAFBLADED_SWORD(ItemID.LEAFBLADED_SWORD),
    LEAFBLADED_BATTLEAXE(ItemID.LEAFBLADED_BATTLEAXE),
    BLACK_MASK(ItemID.BLACK_MASK_10),
    GRANITE_LONGSWORD(ItemID.GRANITE_LONGSWORD),
    GRANITE_BOOTS(ItemID.GRANITE_BOOTS),
    ABYSSAL_DAGGER(ItemID.ABYSSAL_DAGGER),
    UNCHARGED_TRIDENT(ItemID.UNCHARGED_TRIDENT),
    KRAKEN_TENTACLE(ItemID.KRAKEN_TENTACLE),
    DARK_BOW(ItemID.DARK_BOW),
    OCCULT_NECKLACE(ItemID.OCCULT_NECKLACE),
    DRAGON_THROWNAXE(ItemID.DRAGON_THROWNAXE),
    DRAGON_KNIFE(ItemID.DRAGON_KNIFE),
    DRAGON_SWORD(ItemID.DRAGON_SWORD),
    DRAKES_TOOTH(ItemID.DRAKES_TOOTH),
    DRAKES_CLAW(ItemID.DRAKES_CLAW),
    HYDRA_FANG(ItemID.HYDRAS_FANG),
    HYDRA_HEART(ItemID.HYDRAS_HEART),
    HYDRA_EYE(ItemID.HYDRAS_EYE),
    BASILISK_JAW(ItemID.BASILISK_JAW),
    BLOOD_SHARD(ItemID.BLOOD_SHARD),

    // Shared Boss Drops
    DRAGON_2H_SWORD(ItemID.DRAGON_2H_SWORD),
    DRAGON_PICKAXE(ItemID.DRAGON_PICKAXE),
    UNCUT_ONYX(ItemID.UNCUT_ONYX),

    // Grotesque Guardians
    GRANITE_GLOVES(ItemID.GRANITE_GLOVES),
    GRANITE_RING(ItemID.GRANITE_RING),
    GRANITE_HAMMER(ItemID.GRANITE_HAMMER),
    BLACK_TOURMALINE_CORE(ItemID.BLACK_TOURMALINE_CORE),
    JAR_OF_STONE(ItemID.JAR_OF_STONE),

    // Kraken
    TRIDENT_OF_THE_SEAS_FULL(ItemID.TRIDENT_OF_THE_SEAS_FULL),
    JAR_OF_DIRT(ItemID.JAR_OF_DIRT),

    // Thermonuclear Smoke Devil
    SMOKE_BATTLESTAFF(ItemID.SMOKE_BATTLESTAFF),

    // Cerberus
    PRIMORDIAL_CRYSTAL(ItemID.PRIMORDIAL_CRYSTAL),
    PEGASIAN_CRYSTAL(ItemID.PEGASIAN_CRYSTAL),
    ETERNAL_CRYSTAL(ItemID.ETERNAL_BOOTS),
    JAR_OF_SOULS(ItemID.JAR_OF_SOULS),

    // Abyssal Sire
    UNSIRED(ItemID.UNSIRED),

    // Alchemical Hydra
    HYDRA_LEATHER(ItemID.HYDRA_LEATHER),
    HYDRA_TAIL(ItemID.HYDRA_TAIL),
    HYDRA_CLAW(ItemID.HYDRAS_CLAW),
    JAR_OF_CHEMICALS(ItemID.JAR_OF_CHEMICALS),
    ALCHEMICAL_HYDRA_HEADS(ItemID.ALCHEMICAL_HYDRA_HEADS),

    // Chaos Fanatic
    MALEDICTION_SHARD_1(ItemID.MALEDICTION_SHARD_1),
    ODIUM_SHARD_1(ItemID.ODIUM_SHARD_1),

    // Crazy Archaeologist
    MALEDICTION_SHARD_2(ItemID.MALEDICTION_SHARD_2),
    ODIUM_SHARD_2(ItemID.ODIUM_SHARD_2),
    FEDORA(ItemID.FEDORA),

    // Scorpia
    MALEDICTION_SHARD_3(ItemID.MALEDICTION_SHARD_3),
    ODIUM_SHARD_3(ItemID.ODIUM_SHARD_3),

    // King Black Dragon
    KBD_HEADS(ItemID.KBD_HEADS),

    // Vet'ion
    RING_OF_THE_GODS(ItemID.RING_OF_THE_GODS),

    // Venenatis
    TREASONOUS_RING(ItemID.TREASONOUS_RING),

    // Callisto
    TYRANNICAL_RING(ItemID.TYRANNICAL_RING),

    // Other Bosses
    // Dagannoth Supreme
    ARCHERS_RING(ItemID.ARCHERS_RING),
    SEERCULL(ItemID.SEERCULL),

    // Dagannoth Rex
    WARRIOR_RING(ItemID.WARRIOR_RING),
    BERSERKER_RING(ItemID.BERSERKER_RING),

    // Dagannoth Prime
    SEERS_RING(ItemID.SEERS_RING),
    MUD_BATTLESTAFF(ItemID.MUD_BATTLESTAFF),

    // Sarachnis
    SARACHNIS_CUDGEL(ItemID.SARACHNIS_CUDGEL),

    // Kalphite Queen
    KQ_HEAD(ItemID.KQ_HEAD),

    // Godwars
    // Armadyl
    ARMADYL_HELMET(ItemID.ARMADYL_HELMET),
    ARMADYL_CHESTPLATE(ItemID.ARMADYL_CHESTPLATE),
    ARMADYL_CHAINSKIRT(ItemID.ARMADYL_CHAINSKIRT),
    ARMADYL_HILT(ItemID.ARMADYL_HILT),

    // Saradomin
    SARADOMIN_SWORD(ItemID.SARADOMIN_SWORD),
    SARADOMINS_LIGHT(ItemID.SARADOMINS_LIGHT),
    ARMADYL_CROSSBOW(ItemID.ARMADYL_CROSSBOW),
    SARADOMIN_HILT(ItemID.SARADOMIN_HILT),

    // Bandos
    BANDOS_CHESTPLATE(ItemID.BANDOS_CHESTPLATE),
    BANDOS_TASSETS(ItemID.BANDOS_TASSETS),
    BANDOS_BOOTS(ItemID.BANDOS_BOOTS),
    BANDOS_HILT(ItemID.BANDOS_HILT),

    // Zamorak
    STEAM_BATTLESTAFF(ItemID.STEAM_BATTLESTAFF),
    ZAMORAKIAN_SPEAR(ItemID.ZAMORAKIAN_SPEAR),
    STAFF_OF_THE_DEAD(ItemID.STAFF_OF_THE_DEAD),
    ZAMORAK_HILT(ItemID.ZAMORAK_HILT),

    // Other Bosses
    // Zulrah
    TANZANITE_FANG(ItemID.TANZANITE_FANG),
    MAGIC_FANG(ItemID.MAGIC_FANG),
    SERPENTINE_VISAGE(ItemID.SERPENTINE_VISAGE),
    JAR_OF_SWAMP(ItemID.JAR_OF_SWAMP),

    // Vorkath
    SKELETAL_VISAGE(ItemID.SKELETAL_VISAGE),
    DRAGONBONE_NECKLACE(ItemID.DRAGONBONE_NECKLACE),
    VORKATHS_HEAD(ItemID.VORKATHS_HEAD),
    JAR_OF_DECAY(ItemID.JAR_OF_DECAY),

    // Corporeal Beast
    ARCANE_SIGIL(ItemID.ARCANE_SIGIL),
    ELYSIAN_SIGIL(ItemID.ELYSIAN_SIGIL),
    SPECTRAL_SIGIL(ItemID.SPECTRAL_SIGIL),
    HOLY_ELIXER(ItemID.HOLY_ELIXIR),
    SPIRIT_SHIELD(ItemID.SPIRIT_SHIELD),

    // Nightmare
    INQUISITORS_GREAT_HELM(ItemID.INQUISITORS_GREAT_HELM),
    INQUISITORS_HAUBERK(ItemID.INQUISITORS_HAUBERK),
    INQUISITORS_PLATESKIRT(ItemID.INQUISITORS_PLATESKIRT),
    INQUISITORS_MACE(ItemID.INQUISITORS_MACE),
    NIGHTMARE_STAFF(ItemID.NIGHTMARE_STAFF),
    ELDRITCH_ORB(ItemID.ELDRITCH_ORB),
    VOLATILE_ORB(ItemID.VOLATILE_ORB),
    HARMONISED_ORB(ItemID.HARMONISED_ORB),
    JAR_OF_DREAMS(ItemID.JAR_OF_DREAMS),

    // Skotizo
    DARK_CLAW(ItemID.DARK_CLAW),
    JAR_OF_DARKNESS(ItemID.JAR_OF_DARKNESS),

    // Obor
    HILL_GIANT_CLUB(ItemID.HILL_GIANT_CLUB),

    // Bryophyta
    BRYOPHYTAS_ESSENCE(ItemID.BRYOPHYTAS_ESSENCE),

    // Zalcano
    CRYSTAL_TOOL_SEED(ItemID.CRYSTAL_TOOL_SEED),
    ZALCANO_SHARD(ItemID.ZALCANO_SHARD),

    // Miscellaneous
    DRAGON_WARHAMMER(ItemID.DRAGON_WARHAMMER),
    LONG_BONE(ItemID.LONG_BONE),
    CURVED_BONE(ItemID.CURVED_BONE),
    DRAGON_FULL_HELM(ItemID.DRAGON_FULL_HELM),
    DRAGON_METAL_SLICE(ItemID.DRAGON_METAL_SLICE),
    DRAGON_METAL_LUMP(ItemID.DRAGON_METAL_LUMP),
    DRAGON_LIMBS(ItemID.DRAGON_LIMBS),
    ;


    private final int id;

    public int getId()
    {
        return id;
    }
}
